### ISSUE TITLE
Inferring vocabs failure?

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#131]
With the code
```
import nengo_spa as spa

dim = 32
vocab = spa.Vocabulary(dimensions=dim)

words = ['ORANGE', 'APRICOT', 'CHERRY', 'STRAWBERRY', 'APPLE']

for word in words:
    vocab.populate(word)

with spa.Network('AssociativeMemory', seed=1) as model:
    a = spa.State(dim)
    
    model.assoc_mem = spa.ThresholdingAssocMem(threshold=0.3, input_vocab=vocab)
    a >> model.assoc_mem
```

I get the error
```
Traceback (most recent call last):
  File "/home/saubin/git/nengo_gui/nengo_gui/page.py", line 220, in execute
    exec(compiled, code_locals)
  File "<nengo_gui_compiled>", line 15, in <module>
  File "/home/saubin/git/nengo_spa/nengo_spa/network.py", line 115, in __rshift__
    return as_ast_node(self) >> as_sink(other)
  File "/home/saubin/git/nengo_spa/nengo_spa/actions.py", line 35, in __rrshift__
    infer_types(self, other)
  File "/home/saubin/git/nengo_spa/nengo_spa/ast/base.py", line 14, in infer_types
    type_ = coerce_types(*[n.type for n in nodes])
  File "/home/saubin/git/nengo_spa/nengo_spa/types.py", line 148, in coerce_types
    "Incompatible types: " + ", ".join(str(t) for t in types))
nengo_spa.exceptions.SpaTypeError: Incompatible types: TVocabulary<32-dimensional vocab at 0x7f507563fcc0>, TVocabulary<32-dimensional vocab at 0x7f5074f82278>
```

Is it reasonable to expect inference about both modules using the same vocabulary? If not, could this error message be improved to reflect the actual reason for this error?

**Comment by jgosmann** [comment]
> Is it reasonable to expect inference about both modules using the same vocabulary?

I don't think so. It would require to add the keys from `vocab` to the default vocabulary with `dims` dimensions. This has been an annoying an surprising behaviour in the old SPA. Also it is not clear whether a `reinterpret` or `translate` should be used.

The example is easily fixed by using `spa.State(vocab)` or alternatively populating the default vocab and using that for the associative memory.

> If not, could this error message be improved to reflect the actual reason for this error?

Maybe, what do you think would be a better message? To me it reflects the actual reason (at least from a technical point of view).

**Comment by Seanny123** [comment]
In my weakly held opinion, it might be worthwhile to note when an error is caused due to mismatched dimensions vs. types vs. different vocabularies. However, I would encourage waiting until this comes up again before making the change.

**Comment by jgosmann** [comment]
That could be implemented.

**Comment by Seanny123** [comment]
Yep!
