### ISSUE TITLE
Add possibility to access networks constructed through SPA syntax

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#135]

**Comment by Seanny123** [comment]
What did you mean by this issue? Did you mean beyond just looking at `model.objects`? What structure were you hoping for?

**Comment by jgosmann** [comment]
> Did you mean beyond just looking at model.objects?

Yes.

> What structure were you hoping for?

I don't know, that is something to think about to resolve this issue.

**Comment by jgosmann** [comment]
Providing the access to the constructed networks isn't straight-forward and I cannot think of a good way to do it. Thus, I am probably going to close this issue unresolved. If access to the constructed networks is required, there is always the option to manually create the networks or go through `model.objects`. Also, not exposing the constructed networks prevents user from relying to much on the implementation details in case these change in the future.
