### ISSUE TITLE
Add support for scalars changing over time

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#139]
## Problem

`spa.Transcode` won't allow for scalar inputs, so there's no way to input a time-varying scalar input with the `spa.Actions` syntax.

For example, if I make a custom module with a scalar input:
```
class GatedMemory(spa.Network):

    vocab = VocabularyOrDimParam('vocab', default=None, readonly=True)
    neurons_per_dimension = IntParam(
        'neurons_per_dimension', default=200, low=1, readonly=True)
    
    def __init__(self, vocab=Default, neurons_per_dimension=Default, **kwargs):
        super(GatedMemory, self).__init__(**kwargs)
        
        self.vocab = vocab
        self.neurons_per_dimension = neurons_per_dimension
    
        with self:
            self.mem = workingmemory.InputGatedMemory(
                self.neurons_per_dimension, self.vocab.dimensions)
        
        self.input = self.mem.input
        self.gate = self.mem.gate
        self.reset = self.mem.reset
        self.output = self.mem.output
        
        self.declare_input(self.input, self.vocab)
        self.declare_input(self.gate, None)
        self.declare_input(self.reset, None)
        self.declare_output(self.output, self.vocab)
```

I'm going to have a problem routing something to `gate` or `reset`, other than a constant input, using the `spa.Actions` syntax.

```
dimensions = 32

model = spa.Network()

with model:
    model.spa_in = spa.Transcode("OKAY", output_vocab=dimensions)
    model.g_mem = GatedMemory(dimensions)
    
    model.spa_in >> model.g_mem
    0 >> model.g_mem.gate
```

## Possible Solution: New Module

Make a module called `spa.ScalarNode(func)` which allows for time-varying inputs and outputs.

## Possible Solution: Modify `spa.Transcode`

Allow to specify the `output_vocab` or `input_vocab` as `1` thus indicating returning a scalar? This feels a little bit like over-loading a concept.

## Possible Solution: Allow any Nengo object with a 1D output to be used

Somehow?

**Comment by Seanny123** [comment]
@tcstewar do you have any opinions on this?

**Comment by jgosmann** [comment]
I'm in favour of allowing any Nengo object with 1D output.

**Comment by Seanny123** [comment]
How exactly would you accomplish this? I ask, because I can't tell if this is something I can edit myself or not.

**Comment by jgosmann** [comment]
The overloaded `>>` operator converts is arguments to AST nodes (with the `as_node` or similar called function). That just needs to extended to convert Nengo objects with 1D size out into a scalar `ModuleOutput`.
