### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#140]
We should add the Nengo branding where appropriate. [This includes picking a color for Nengo SPA.](https://github.com/nengo/design/blob/src/guidelines.rst#project-branding) Suggestions welcome.

**Comment by Seanny123** [comment]
How about the color `#D40000`? This is what it looks like in the logo (I'm going to change the text later):
![image](https://user-images.githubusercontent.com/1918825/39025533-84369fc6-43fc-11e8-9e35-fe4040404427.png)

This is what it looks like in a dark background:
![image](https://user-images.githubusercontent.com/1918825/39025512-6b77368a-43fc-11e8-91a6-1e4a816fafe9.png)

This is what the dark logo looks like:
![image](https://user-images.githubusercontent.com/1918825/39025593-dec1c4b6-43fc-11e8-8cde-3e4d79d007f4.png)

**Comment by celiasmith** [comment]
oooo, looks nice!

**Comment by jgosmann** [comment]
I'm sold! Red is my favourite color and it matches the color of ‘brain‘ on the “How to build a brain book”.

**Comment by Seanny123** [comment]
Here's the logo with the text edited:

![image](https://user-images.githubusercontent.com/1918825/39085187-0e195de0-454d-11e8-9ff4-14539d1e55b7.png)

I thought the serifs were a little strong, so I tried reducing them:

![image](https://user-images.githubusercontent.com/1918825/39085181-f91862f6-454c-11e8-9344-07c17c03a4e1.png)

How do people feel about the Roboto Slab font?

**Comment by Seanny123** [comment]
I'm having a really hard time finding non-serif fonts that don't look too cartoon-like. Do [any of these fonts](https://fonts.google.com/selection?category=Sans+Serif,Display,Monospace&selection.family=Anton|Black+Han+Sans|Cabin|Do+Hyeon|Jua) appeal to you? May I defer the font selection to you?

**Comment by jgosmann** [comment]
I think, I am pretty happy with the Roboto font. It has a similar emphasize on geometrical shapes as Sanchez.
![full-logo-light](https://user-images.githubusercontent.com/850157/39150051-0fb099fc-470f-11e8-835d-1c398444ac01.png)

I adjusted the letter spacing to match to the letter spacing in ‘Nengo’ and made a gap inbetween the two logo components about twice a wide as the letter spacing for additional visual separation.

I also had the idea of trying a “box” design. Not sure whether that is allowable under the branding guide lines (@tbekolay?). I made a mockup below (for a final version I would do a more precise alignment and fine tune the corner radius). But I'm not that convinced on it. I feel like something is missing to make it actually look good, but I'm not sure what that is. Maybe the red needs to be darker or lighter as now a larger area is filled (which changes the perception)? Or maybe it is the hard contrast of the black and white letters?

![full-logo-light-box](https://user-images.githubusercontent.com/850157/39150058-16440c5e-470f-11e8-9f65-f30e5bd1625b.png)

**Comment by tbekolay** [comment]
Box is a-okay; I seem to recall that I used a box in some mockup of a Nengo GUI logo so allowing that kind of thing is something I had in mind.

**Comment by jgosmann** [comment]
btw: I think really good sans-serif can be quite hard to find. I suppose without the serifs it is hard to make a font that looks distinctive (and not generic like any other sans-serif font), but at the same time remains elegant and doesn't drift into what @Seanny123 described as cartoon-like. Personally I find the sorting by popular instead of trending fonts on fonts.google.com gives better fonts (but also fonts that are used a lot and might thus be overused; though I rather use a *good* overused font than a bad font).

**Comment by Seanny123** [comment]
Personally, I like the logo better without the box, but I'm also unsure why. I think it might be the switching between white and black letters is throwing me off?

**Comment by jgosmann** [comment]
I added grading to the tuning curves and adjusted the kerning between the P and A (the gap appeared larger than the gap between the S and P to me). I'd be happy to use this as the final logo.

![full-logo-light](https://user-images.githubusercontent.com/850157/39197785-6c15f4f4-47b3-11e8-9688-9bc35e264305.png)

**Comment by tbekolay** [comment]
Looks good to me :+1: We can discuss in the design repo whether the grading should be standardized or left to each logo designer.

**Comment by Seanny123** [comment]
I am also happy with this as the final logo! I'll make a PR on the design repo which you can add your version of the full logo.

**Comment by Seanny123** [comment]
Given the design repo PR has been merged, I'm going to go ahead and close this issue.
