### ISSUE TITLE
Updating various dev-ops things to the new format in Nengo

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#145]
Should we make the changes that `nengo/nengo` made? Specifically:

- Putting the requirements inside `setup.py` instead of the text files
- Refactoring the `.travis.yml` file into separate shell scripts
- Running `codespell -q 3` to avoid typos

Somewhat related to #143 and #96

**Comment by jgosmann** [comment]
Fine with me, PRs welcome.
