### ISSUE TITLE
Styles missing from published documentation

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#154]
The style sheet for the documentation published by the Travis CI build seems to be missing.
https://www.nengo.ai/nengo-spa/

**Comment by jgosmann** [comment]
I don't know what the problem is. The [files are all there](https://github.com/nengo/nengo-spa/tree/gh-pages/_static/css), but trying to [access via the nengo.ai URL](https://www.nengo.ai/nengo-spa/_static/css/theme.css) gives a 404 though all the HTML files seems to work fine. The same URL schema is working for Nengo DL and was working before when I manually pushed the documentation (instead of relying on the Travis CI build). Any idea what's wrong, @tbekolay?

**Comment by tbekolay** [comment]
You need add the [`sphinx.ext.githubpages` extension](https://github.com/nengo/nengo/blob/master/docs/conf.py#L38), which puts the `.nojekyll` file in there. Right now Github Pages is running Jekyll on top of Sphinx.
