### ISSUE TITLE
Is the Scalar module still needed?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#166]
With #157 (fixing #139) normal Nengo nodes and ensembles can be used for scalar values. Do we still need the `Scalar` module? If not, should we remove it?

**Comment by Seanny123** [comment]
I didn't notice it at the time, but I do think it can be removed. I can't think of any meaningful distinction between `spa.Scalar` and a passthrough `nengo.Node()`.

**Comment by jgosmann** [comment]
There might be places where scalar nodes are created automatically in which case it provides the configuration for the neuron number.

**Comment by jgosmann** [comment]
[When routing scalar information it is still used.](https://github.com/nengo/nengo-spa/blob/054545f6ec8d4e58c25d8e8cde8603b14a2a26e9/nengo_spa/modules/thalamus.py#L189)

I think we should keep it for now.

Also this does not work:
```python
ens = nengo.Ensemble(50, 1)
0 >> ens
```
