### ISSUE TITLE
Should transcode allow scalars 0 and 1?

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#176]
For the zero and identity vector.

**Comment by jgosmann** [comment]
Some thoughts:

The main question here is what could potentially go wrong?

* Are there any situations where it is not clean how the integer output should be interpreted? In other words, could there be a situation where we want 0 and 1 to mean the actual numbers instead of zero and identity vector?
* How should the floats `0.` and `1.` be handled?
* Other numbers should raise errors I assume?

Note that currently we do not allow `0 >> state` or `1 >> state`. Allowing this in the Transcode function only would be inconsistent ... but allowing it there would require to consider more cases and has a higher risk of introducing problems.

Also note that there are currently other ways to achieve the same thing:
* Returning strings `'0'` or `'1'`.
* Returning `spa.pointer.Zero(d)` or `spa.pointer.Identity(d)`.

**Comment by jgosmann** [comment]
Also, the string return values were from before we switched the syntax. Maybe we should deprecate string return values and move to symbolic expressions?

**Comment by jgosmann** [comment]
@tcstewar Do you have any thoughts on this?

**Comment by tcstewar** [comment]
Hmmm...  good question.  I'd say that if we do allow 0 and 1, we should also allow 0.5 and 2.0 and all those as well -- they'd be all scaled values of the identity matrix.  Basically, I'd expect people to be surprised if 0 worked and 1 worked, but no other integer and no float values worked.

I would also say that if we did allow it, then we should allow `1 >> state` and the like as well.  Otherwise I have to remember what situations allow what possibilities. 

Hmm...  I'm not sure about it, but I think I'm leaning towards allowing them.  It is definitely handy to be able to return `0`, and it seems weird that to do it you either have to use `'0'` (when you don't have to use string syntax anywhere else), or the `spa.pointer.Zero(d)` approach (which has a very different syntax than everything else and requires you to know the number of dimensions).

**Comment by tcstewar** [comment]
(note: I could also see an argument for *only* allowing `0` as a return, and not allowing `1`.  But I do think if we allow `1` we should also allow any int or float.)

**Comment by jgosmann** [comment]
We do allow
``python
scalar = spa.Scalar()
0 >> scalar
```
Does that change your opinion on
```python
state = spa.State(...)
0 >> state
```
@tcstewar?

It introduces a little bit less type safety, but I think I might be ok with.

**Comment by jgosmann** [comment]
I guess there is a number of cases that need to be considered and in some it is ambiguous what is supposed to happen.
1. `0.5 + spa.sym.A`: Fail? (but why should this fail if `0.5 >> state` is allowed) Add `0.5*Identity` to `A`?
2. `spa.dot(0.5, spa.sym.A)` Fail? Dot product with `0.5*Identity`? (Scalar product? but that would be weird given the explicit dot)
3. `0.5 * spa.sym.A`: Scalar product! But if `0.5 + spa.sym.A` adds `0.5*Identity` to `A`, why would this not do circular convolution of `0.5*Identity` and `A`?

In `vocab.parse` 1. fails, there is no notation for 2, and 3 is a scalar product. Parsing a single number will give a scaled identity. I think the behaviuour in `vocab.parse` and in the action rules should be consistent. This would mean to disallow `0.5 + spa.sym.A`, but allow `0.5 >> state`. But we could also change `vocab.parse` to not allow single numbers. This means that `vocab.parse` could not be used to easily obtain the identity (or zero) vector. However, the current set of rules is inconsistent anyways, because there is currently no way to explicitly parse the sum of the identity with another vector (because `'0.5 + A'`) is not allowed. Maybe some other way of denoting the special elements like identity is required.

**Comment by jgosmann** [comment]
I definitely feel like we're trading off convenience against (mathematical/type system) purity. The problem with loosing purity is that it can make things harder to reason about (e.g. how will a number be interpreted in different contexts?) and can easily lead to corner cases where these type heuristics break down.

**Comment by jgosmann** [comment]
> (note: I could also see an argument for only allowing 0 as a return, and not allowing 1. But I do think if we allow 1 we should also allow any int or float.)

Thinking about #187 made me wonder about the following option:

* Do not allow to use pure numbers such as `0` or `1` as shorthands for semantic pointers. This keeps the types clean because numbers are only ever used as scalars. It neatly handles the three cases above: 1. addition is disallowed (scalar + SP is not a defined operation), 2. is disallowed (dot product requires both operands to be SPs), 3. is allowed as scalar product with SP is defined and not ambiguity with different meaning in addition is given.
* Treat `None` as the zero vector. The semantic meaning of the word `None` and the zero vector are similar. It is unambiguously not a scalar. Depending on how #187 is resolved, `None` will not be allowed as a Semantic Pointer name (i.e. it is already a reserved name).
* There won't be a shorthand for the identity vector (except `spa.pointer.Identity(d)`). But I rarely need the identity vector, a zero vector output is much more common.
* One other thing that is either neat or a potential pitfall: A Python function that ends without a return statement (or a `return` statement without return value) will return `None`. Thus, without a return value you get the zero vector automatically. That makes sense, but could also silence the problem of a forgotten return value.

**Comment by jgosmann** [comment]
Thoughts, @Seanny123 + @tcstewar?

**Comment by jgosmann** [comment]
Final question: Should we disallow returning string expressions?

**Comment by Seanny123** [comment]
> Final question: Should we disallow returning string expressions?

When I first encountered automatically parsed strings in `spa.Input` (which is the basis for `spa.Transcode`), it really confused me. Additionally, this would allow for throwing errors early and obviously. Consequently, I feel like it would be a good idea to trade-off boiler-plate code for understanding in this case. However, I don't feel *super* strongly about it.

**Comment by jgosmann** [comment]
One potential problem with allowing `None` for the the `Zero` vector: You cannot do things like `3 * None`.

Maybe we should treat the semantic pointer names `Identity`, `AbsorbingElement`, and `Zero` specially, so that you could use `spa.sym.Zero`

**Comment by Seanny123** [comment]
> Maybe we should treat the semantic pointer names Identity, AbsorbingElement, and Zero specially, so that you could use spa.sym.Zero

Personally, I like this approach better than just a bare `None`, but it's only a slight preference.

**Comment by jgosmann** [comment]
> Final question: Should we disallow returning string expressions?

Any opinions? It is partly a left over from older SPA versions, but maybe still convenient?

**Comment by jgosmann** [comment]
It doesn't seem harmful to me to allow strings as basically a shorthand for `spa.sym(string)`.
