### ISSUE TITLE
Limiting what can be assigned to declared inputs and outputs

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#181]
Today, I saw a student do:

```
comp = spa.Compare()
comp.input_a = spa.sym("A")
```

This doesn't throw an error, but should it at least give a warning?

**Comment by jgosmann** [comment]
I'm somewhat on the fence. Python allows you to redefine attributes of objects and we can't possibly catch all the cases where Python allows you to do things that you might not have intended.

**Comment by tbekolay** [comment]
We do this on Nengo objects ([here](https://github.com/nengo/nengo/blob/master/nengo/base.py#L100)). The PR for it was https://github.com/nengo/nengo/pull/393 and was based on discussion in https://github.com/nengo/nengo/issues/217, for context.

**Comment by jgosmann** [comment]
We only do it for non-existing attributes though. Actually this makes me wonder, whether this might be something to implement in Nengo rather than Nengo SPA.

**Comment by tbekolay** [comment]
Oh, I didn't realize `input_a` was an existing attribute. Perhaps we could make these attributes `NengoObjectParam`s? Which could be readonly if you don't want the user to be able to overwrite them.

**Comment by jgosmann** [comment]
We're not doing that in core Nengo networks, so it feels weird to me to do in Nengo SPA networks.

**Comment by tbekolay** [comment]
Yep that's fair. I could see doing it in the Nengo networks, but that would require switching them all to be subclasses, so probably needs more thought.

**Comment by jgosmann** [comment]
Closing as a core Nengo issue.
