### ISSUE TITLE
vocab.parse handles some reserved Python keywords incorrectly

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#187]
`vocab.parse('None')` gives `SpaParseError: The result of parsing 'None' is not a SemanticPointer.` instead of returning the Semantic Pointer named `None` or giving the correct error (if non-existent in strict vocab): `SpaParseError: Error parsing expression 'None' with 16-dimensional vocab at 0x7fc67d306e10: name 'None' is not defined`.

`vocab.parse('True')` and `vocab.parse('False')` will give the identity and zero vector respectively instead of the appropriate Semantic Pointer or error.

Note that this is somewhat related to #176.

**Comment by jgosmann** [comment]
We said the a Semantic Pointer name must be “a valid Python 2 identifier starting with a capital letter”. `None`, `True`, and `False` are keywords and thus not allowed as “ordinary identifiers”. Thus, the easiest option might be to disallow these as Semantic Pointer names?

**Comment by tcstewar** [comment]
> Thus, the easiest option might be to disallow these as Semantic Pointer names?

Seems reasonable to me...  possibly surprising, though, but a good error message should make it clear.   And perhaps another reason to encourage the use of ALL_CAPS in our examples....  :)
