### ISSUE TITLE
Naming inconsistencies

### ISSUE THREAD

**Issue by jgosmann** [nengo/nengo-spa#199]
Not all modules are named like the main class they contain and different abbreviated forms are used (CircularConvolution, cconv, etc). All of this should follow a coherent structure.

**Comment by jgosmann** [comment]
Here is my concrete proposal for renames (based on #198):

* `nengo_spa.actions` to `nengo_spa.action_selection`
* `nengo_spa.pointer` to `nengo_spa.semantic_pointer`
* `nengo_spa.vocab` to `nengo_spa.vocabulary`
* `nengo_spa.modules.assoc_mem` to `nengo_spa.modules.associative_memory`
* `nengo_spa.algebras.cconv` to `nengo_spa.algebras.hrr_algebra` and `CircularConvolutionAlgebra` to `HrrAlgebra`
* `nengo_spa.algebras.vtb` to `nengo_spa.algebras.vtb_algebra`

This makes all module names to match the main class in those modules (except where modules are a collection of multiple things of equal importance such as `nengo_spa.math` or `nengo_spa.networks.selection`). Most of these module names are never referenced by the user as all these classes are usually availlible from the parent module (e.g. `nengo.networks`) if not the root `nengo_spa` module. Furthermore, `HrrAlgebra` is shorter than `CircularConvoluitionAlgebra` and maybe expresses more that it is *elementwise addition* and *circular convolution* that together define the algebra.

@Seanny123 @tcstewar

**Comment by Seanny123** [comment]
Legit.
