### ISSUE TITLE
Type comparisons should use `is` instead of `==`

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#204]
In https://github.com/nengo/nengo-spa/blob/master/nengo_spa/ast/dynamic.py there's a bunch of comparisons that are `if self.type == TScalar`. Should they be replaced by `if self.type is TScalar`? Is that something Pylint checks for?

It's probably not important, but I thought I would make a quick note of it.

**Comment by pblouw** [comment]
Not sure about pylint, but I think the use of value comparisons rather than object comparisons to do type-checking is intentional and consistent, given that all of the type classes implement custom `__eq__` methods.

**Comment by Seanny123** [comment]
You're absolutely correct @pblouw
