### ISSUE TITLE
Synapses for different thalamic channels

### ISSUE THREAD

**Issue by tcstewar** [nengo/nengo-spa#21]
In Jelmer's model, he's finding that he would like to adjust the synapse times between areas separately for different thalamic actions.

Right now, the thalamus has a single parameter `synapse_channel` that sets it for all of them.  He's added a hack that adds this parameter:

```
synapse_channel_dict : dict, optional (Default: None, uses synapse_channel for all channels)
        Set synaptic filter per state or channel between two states. 
        E.g. dict(vision=.01, goal_memory=.05, memory=.1) means:
        1) synaptic filters *to* the object 'vision' are set to .01
        2) the synaptic filter from 'goal' to 'memory' are set to .05
        3) synaptic filters to 'memory' not originating in 'goal' are set to .1
        4) all other synaptic filters on channels are set to “synapse_channel"
```

I think I'd prefer some slightly different notation (maybe something like: `synapse_channel_dict={model.vision:.01, (model.goal, model.memory):.05, model.memory:0.1}`, or maybe some other completely diffeerent approach, but this sort of feature would be nice to have.

**Comment by jelmerborst** [comment]
I would keep the notation consistent with cortical/BG rules, given that it's part of the specification of the thalamus. What about `synapse_channel_dict={'vision':.01, ('goal', 'memory'):.05, 'memory':0.1}`?

Alternatively, would it be possible to change synapse times for connections created cortically or in the thalamus afterwards with an extra function? The advantage of that is that we would only have one specification of synapse times (currently, you would have to do this separately for cortical connections and thalamus).

**Comment by jgosmann** [comment]
> Alternatively, would it be possible to change synapse times for connections created cortically or in the thalamus afterwards with an extra function?

That should be possible, but is currently prevented by #22. I want to get that working first. I'm not sure if I want to introduce a more complicated parameter for this because it could be a slippery slope of introducing such parameters for a lot more things.

**Comment by jgosmann** [comment]
Setting the synapses for those connections is already possible. When building the action rules with `actions.build()` a tuple `(bg, thalamus, constructed)` is returned. `bg` and `thalamus` are the basal ganglia and thalamus objects. These provide access to a number of connections, in particular, `thalamus.channel_out.connections` contains all the outgoing connections from channels. Furthermore, `constructed` is a dictionary mapping nodes in the abstract syntax tree constructed from the rules to constructed objects and will contain the connections going into a channel. It is not clear on which of those two connections you want to change the synapse for (and this is also a problem with the proposed syntax).

To change the outgoing connections of the channel you could do something like:
```python
for conn in thalamus.channel_out_connections:
    if conn.post is model.vision.input:
        conn.synapse = nengo.Lowpass(0.01)
    elif conn.post is model.memory.input:
        conn.synapse = nengo.Lowpass(0.1)
    # TODO figure out some way to detect if a connection originates from goal
```

To change the incoming connections of the channel you could do something like this:
```python
for node, objs in constructed.items():
    if isinstance(node, nengo_spa.spa_ast.Effect):
        if node.sink == 'vision':
            synapse_tau = 0.01
        elif node.sink = 'memory':
            if node.source = 'goal':
                synapse_tau = 0.05
            else:
                synaspe_tau = 0.1
        for obj in objs:
            if isinstance(obj, nengo.Connection):  # should actually be all connections, but better to be safe than sorry
                obj.synapse = nengo.Lowpass(synapse_tau)
```

**Comment by jelmerborst** [comment]
That is useful, thanks. I do think it would be nice to be able to specify it when constructing these items, but this could also work.

> It is not clear on which of those two connections you want to change the synapse for (and this is also a problem with the proposed syntax).
With my hack I changed the synapse for both connections - that was indeed one of the problems I encountered.

**Comment by jgosmann** [comment]
Another problem coming up with syntax for doing this on construction time is that the right-hand side of an effect can be an arbitrary expression (e.g. 'a = b * c + d'). That means that expression needs somehow to be matched against the syntax tree. Also, the `Thalamus` methods creating the connections don't know the names of the things they are connecting to. All of this adds up to a lot af complications for a proper implementation. I would rather improve the access to the constructed objects easier to make such manipulations easier. In fact, the current implementation of that is just an initial attempt to allow access to the constructed objects at all. Not a lot of thought went into making this more convenient to use. So ideas how to improve this are welcome.

**Comment by jgosmann** [comment]
It's been a while and the SPA syntax has changed a bit, but it still seems hard to integrate the capability for different synapses for the channels in a consistent manner. If no one has a good suggestion, I am probably going to close this with the note that synapses can be changed after the creation of the channels. With the newer syntax the thalamus is created by an `ActionSelection` object that allows the access to the channels as `action_selection.thalamus.channels`. The input/output nodes of the channels can be used to identify the connections that need to be adjusted.
