### ISSUE TITLE
Semantic pointer names may consume all RAM when iterating/recursing

### ISSUE THREAD

**Issue by arvoelke** [nengo/nengo-spa#244]
Self-binding to a depth of 20-30 can easily consume all of the available RAM (the example here is 33MB but in my application it was consuming 38GB of RAM). Specifically, iteratively/recursively building up a semantic pointer may cause its `name` to grow exponentially in length. I accidentally 'crashed' my desktop a few times trying to figure out what was going on here. Minimal example:

```python
import nengo_spa
import numpy as np

n_iter = 20  # warning: don't set this any higher

sp = nengo_spa.SemanticPointer(np.ones(8), name="X").unitary()
for i in range(n_iter):
    sp += sp * 0.123456789
 
print("%dMB - %s..." % (len(sp.name) / (1024**2), sp.name[:128]))
```

```
33MB - (((((((((((((((((((((X).unitary())+(((X).unitary())*(0.123456789)))+((((X).unitary())+(((X).unitary())*(0.123456789)))*(0.123456...
```

**Comment by jgosmann** [comment]
My first instinct is to limit the length of the generated name. It's solely to give the Semantic Pointer a human recognizable name, but that function is lost at a certain length anyways.

**Comment by arvoelke** [comment]
Great, I've suggested PR #246 to truncate the names.
