### ISSUE TITLE
Minor Typo in SPA Intro User Guide spa-intro.html

### ISSUE THREAD

**Issue by learnnshare** [nengo/nengo-spa#277]
Minor Typo in page: in www.nengo.ai/nengo-spa/user-guide/spa-intro.html.
Control is largely captured by the basal ganglia aciton selection element
Word action is spelled wrong (aciton). very minor - but just thought of mentioning it.

also another typo in same page
or instance given the following input [1] [11] [111] [2n [22] [222] [3] [33] ?
It should be just 2 not 2n

**Comment by jgosmann** [comment]
Thank you for letting me know, a fix is underway: #278
