### ISSUE TITLE
Change example to use examine.similarity

### ISSUE THREAD

**Issue by Seanny123** [nengo/nengo-spa#33]
Certain examples use something like `vocab.parse(pointer).dot(sim.data[conv].T)` when they should be using `examine.similarity`? I'm not sure about this and I'm just making a note as I review some pull requests.

**Comment by jgosmann** [comment]
`examine.similarity` computes the dot product with all Semantic Pointers in the vocabulary. `vocab.parse` only with a single one (or a single expression). So both are for slightly different use cases. Definitely something to look out for when going through the examples to update them.

**Comment by jgosmann** [comment]
There are only two instances using `vocab.parse(pointer).dot(...)` and those cannot be reasonably replaced with `examine.similarity` at the moment.
